[package]
name = "blendbeats"
version = "0.1.0"
edition = "2024"

[dependencies]
rspotify = { version = "0.12", features = ["client-reqwest", "env-file", "cli"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
env_logger = "0.11.8"
tiny_http = "0.12.0"
open = "3.2"
url = "2.3"
